### ISSUE TITLE
Testnet bech32 not sending

### ISSUE THREAD

**Issue by Fonta1n3** [coreyphillips/moonshine#53] opened 2020-05-25 13:40 UTC
I get an error when trying to sweep from and to a testnet bech32 address. When i copy the hex and broadcast elsewhere it looks like there are no inputs. That’s on iOS, latest Testflight.

**Comment by coreyphillips** [comment] 2020-05-25 18:19
Hey, thanks for reaching out. Sorry to see you're experiencing this issue. Unfortunately, I haven't been able to successfully reproduce this on my end yet. My steps for testing this are as follows:
1. Send tBTC to a testnet bech32 address
2. Press the camera icon and scan a qrcode of the private key
3. Set the fee and press the "Sweep" button

If you have specific steps to reproduce this issue that differ from the steps above please send them over. Otherwise, I will continue to keep an eye out and test for it. For reference, I'm testing with Testflight version 0.3.5 (2).

**Comment by Fonta1n3** [comment] 2020-05-26 01:36
My steps to reproduce are:
Receive testnet btc to bech32 address.
Wait for a confirmation.
Tap send.
Tap max amount (thats what I meant by sweeping).
Then it builds the transaction but always get an error when sending. When parsing the ra hex it appears there are no inputs.
Thanks!

**Comment by coreyphillips** [comment] 2020-05-27 20:44
Hey, thanks for the clarification. Unfortunately, I still haven't been able to reproduce this issue on my end. However, I will continue to keep an eye out and test for it.

**Comment by coreyphillips** [comment] 2020-07-28 21:30
Still unable to reproduce on my end. Closing this issue for now.

**Closed by coreyphillips** 2020-07-28 21:30 UTC
Labels: bug
