### ISSUE TITLE
Connecting to custom electrumx server never happen in Release mode

### ISSUE THREAD

**Issue by cryply** [coreyphillips/moonshine#37] opened 2020-03-11 16:22 UTC
I tested your app in debug mode with my custom electrumx server  - works well.
But if I make signed APK with bundled react native it never connect to my Electrumx server.
While sniffing traffic on server side - 
It  shows that Android tries to connect but connection finished without server received payload from mobile phone.

**Comment by coreyphillips** [comment] 2020-03-11 19:57
Interesting. Some troubleshooting questions:

- I'm assuming you're using the correct port/protocol?

- Are you able to connect successfully using the app from the play/app store?

- Are you able to connect successfully using another app/program outside of your network?

**Comment by cryply** [comment] 2020-03-11 20:50
1, yes it works perfectly in emulator or on device in debug mode with Metro server.
2. no. same behavior.
3. sure 

const ElectrumCli = require('electrum-client')
const main = async () => {
    const ecl = new ElectrumCli(50002, 'e0.cranepay.io', 'tls') // tcp or tls
    await ecl.connect() // connect(promise)
    ecl.subscribe.on('blockchain.headers.subscribe', (v) => console.log(v)) // subscribe message(EventEmitter)
    try{
        const ver = await ecl.server_version() // json-rpc(promise)
        console.log(ver)
    }catch(e){
        console.log(e)
    }
    await ecl.close() // disconnect(promise)
}
main()

this script is working.

same as this shell commands:

echo '{"jsonrpc":"2.0","method":"server.version","params":[],"id":1}' | nc e0.cranepay.io 50001

**Comment by cryply** [comment] 2020-03-11 20:52
![image](https://user-images.githubusercontent.com/36797566/76462784-8bf3f080-63e2-11ea-8ee6-d8d14fd7e092.png)
this is in DEBUG  mode

and this is in RELEASE
![image](https://user-images.githubusercontent.com/36797566/76462839-a201b100-63e2-11ea-9048-5c948e1a9064.png)

**Comment by cryply** [comment] 2020-03-11 21:06
This is my electrumx server source code: https://github.com/kyuupichan/electrumx

**Comment by coreyphillips** [comment] 2020-03-11 23:54
This is awesome. I really appreciate the info provided above, many thanks. After some troubleshooting, it appears that the electrum.pingServer methods in ElectrumOptions.js seem to hang when attempting to test or save an electrum server in release mode as you observed. Since those methods are primarily there to ensure we can at least communicate with the specified server I've swapped them out with electrum.getFeeEstimate for now. The changes can be found [here.](https://github.com/coreyphillips/moonshine/commit/7cecbd738b8c42e781cf43ef2b39e076f7d520aa) With these changes, you should be able to connect to your server as expected, but please let me know if you continue having any trouble. I'll continue testing and communicate any news/updates here as they surface.

**Comment by cryply** [comment] 2020-03-12 18:26
It looks way better! Thanks for quick fix.
Only little problem it is still hanging when u click on "Connected To"  under Wallet Name.

Also maybe u can find it useful:
https://github.com/BlueWallet/BlueWallet/blob/master/BlueElectrum.js
Line 403.
Guys left comment about **dirty hack**. Maybe its relevant. Their wallet is connecting to my electrumx in Release.

**Comment by coreyphillips** [comment] 2020-03-12 20:38
Great catch. That should now be resolved as of [this commit.](https://github.com/coreyphillips/moonshine/commit/9d7db2135b8188e586b38f4672a3ee2ab83f0306)

Interesting little trick, thanks for sending over the link. It seems to be an issue with the pingServer method or how I was using it that I'll need to dig into. 

I'm going to leave this issue open for a little bit longer in case any testers report additional issues. If you continue to have any issues definitely let me know.

**Comment by cryply** [comment] 2020-03-14 11:17
Ur latest commit pretty much does the job! ThaNKS!
I can click now on Connect To.
Only small bug. After I have changed my electrum server, server mentioned in Connect To is some old random one. I clicked on Legacy/Segwit buttons to make it refreshed.

**Comment by cryply** [comment] 2020-03-14 11:34
Also can u rename SSL in Electrum settings to TLS plz

**Comment by coreyphillips** [comment] 2020-03-14 14:47
Nice. Gotcha [here.](https://github.com/coreyphillips/moonshine/commit/7bd579710611da3ed1b63d95fd18cca21ed42b7a)
Glad to hear it's working for you. I'll look into the "Connected To" option. It's expected behavior is to switch to a random electrum server if no custom servers are set every time it's pressed. If a custom server is set it only attempts to reconnect to the set server.
I'm going to close this issue for now, but please let me know if you encounter any additional issues. I'll do what I can to sort them out.

**Closed by coreyphillips** 2020-03-14 14:47 UTC
Labels: bug
